@startuml
!pragma layout smetana
'https://plantuml.com/class-diagram

Object TournamentController
TournamentController --> Main

'RELATIONSHIP BETWEEN CLASSES'
Main *-- Tournament : "has a"
Tournament *-- TournamentPlan : "has a"
Tournament *--  Rounds : "has a"
Tournament *-- FileIO : "has a"
Tournament *-- RankList : "has a"
Tournament o-- Registration
Registration *-- TournamentPlan
RankList o-- Rounds

'FIELDS AND METHODS'
Class Main {
+ static main(String[] args)
'method to run program'
+ void tournamentProgram()
}

Class Tournament {
- FileIO fileIO
- Registration textUI
+ void tournamentProgram()
- void enterRegistration()
- void startTournament()
- void saveTournament()
- void endTournament()
+ void displayRankList()
}

Class Registration {
+ teamRegistration()
+ getUserInput()
+ addTeamNameInput()
+ addPlayerNamesInput()
+ saveInputToFile()
}

Class TournamentPlan {
+ double time
+ date

+ void tournamentPlan(String tournamentDescription)
+ void registerTournament()
+ void displayTournamentPlan()
}

Class Rounds {
+ scanner scan = new Scanner(System.in)
+ int score
+ ArrayList<String> winners
+ ArrayList<String> losers
+ String getWinners()
+ String getLosers()
+ void getRoundInput()
+ void displayRound()
+ void getFinalScore()
}

Class RankList {
+ void displayWinners()
+ void displayLosers()
+ void sortRankList()
+ void displayFinalScore()
+ void getDisplayRankList()
}

Class FileIO {
+ ArrayList<String> data
+ Scanner scan = new scanner : System.in
+ ArrayList<Team> readFileData()
+ void saveFileData()
}



@enduml